#!/bin/bash
set -e

clear
make

testAll=1
TEST=9

if [ $TEST -gt 9 ]; then
  testVar="$TEST"
else
  testVar="0$TEST"
fi

echo "*****************Trace$testVar**************"
cat trace$testVar.txt

echo
echo "*****************Actual**************"
make test$testVar > .actual.txt
perl -pne 's/\(\d{2,}\)/XXX/' .actual.txt > .actual1
cat .actual.txt

echo
echo "**************Expected**************"
make rtest$testVar > .expected.txt
perl -pne 's/\(\d{2,}\)/XXX/' .expected.txt > .expected1
cat .expected.txt

echo
echo "**************Diff output*************************"
# -I ingnore the first line
sdiff -I "^.\/sdriver.pl" -s .actual1 .expected1

if [ $testAll -eq 1 ]; then
  echo 
  echo "**************Previous Tests**********************"
  for((i=1; i <= $TEST; i++)) do
    if [ $i -gt 9 ]; then
      testVar="$i"
    else
      testVar="0$i"
    fi
    echo "Testing trace$testVar.txt"


    make test$testVar > .actual.txt
    perl -pne 's/\(\d{2,}\)/XXX/' .actual.txt > .actual1
    make rtest$testVar > .expected.txt
    perl -pne 's/\(\d{2,}\)/XXX/' .expected.txt > .expected1
    sdiff -I "^.\/sdriver.pl" -s .actual1 .expected1
  done
fi
